// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "ewallet/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: _a0, _a1
func (_m *TransactionUsecase) GetAll(_a0 int, _a1 entity.Query) ([]*entity.Transaction, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []*entity.Transaction
	if rf, ok := ret.Get(0).(func(int, entity.Query) []*entity.Transaction); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, entity.Query) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: req, id
func (_m *TransactionUsecase) TopUp(req entity.TopUpRequest, id int) error {
	ret := _m.Called(req, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.TopUpRequest, int) error); ok {
		r0 = rf(req, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transfer provides a mock function with given fields: req, id
func (_m *TransactionUsecase) Transfer(req entity.TransferRequest, id int) error {
	ret := _m.Called(req, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.TransferRequest, int) error); ok {
		r0 = rf(req, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionUsecase(t mockConstructorTestingTNewTransactionUsecase) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
